version: "3"

services:
  api:
    build:
      context: ./AhoyAPI
    restart: always
    env_file:
      - ./api/api.env
    networks:
      - public-network
      - internal-network
    depends_on:
      - db
  db:
    image: postgres:13.1
    restart: always
    env_file:
      - ./db/db.env
    volumes:
      - /var/lib/postgresql/data
      - ./db/scripts:/scripts:ro
    networks:
      - internal-network

# Define an internal network so that the database is completely disconnected from the public Internet.
networks:
  internal-network:
    internal: true
  public-network: